const randonData = [
  {
    id: 1,
    first_name: "Mariette",
    email: "mnerheny0@zimbio.com",
    gender: "Female",
    dates: "2022-12-01",
  },
  {
    id: 2,
    first_name: "Candy",
    email: "cneathway1@craigslist.org",
    gender: "Female",
    dates: "2022-12-02",
  },
  {
    id: 3,
    first_name: "Annnora",
    email: "aingliss2@intel.com",
    gender: "Genderqueer",
    dates: "2022-12-03",
  },
  {
    id: 4,
    first_name: "Juli",
    email: "jjandl3@joomla.org",
    gender: "Female",
    dates: "2022-12-04",
  },
  {
    id: 5,
    first_name: "Travus",
    email: "tnunson4@un.org",
    gender: "Male",
    dates: "2022-12-05",
  },
  {
    id: 6,
    first_name: "Ladonna",
    email: "lsmedmoor5@oracle.com",
    gender: "Female",
    dates: "2022-12-06",
  },
  {
    id: 7,
    first_name: "Mathew",
    email: "mhugnin6@usgs.gov",
    gender: "Male",
    dates: "2022-12-07",
  },
  {
    id: 8,
    first_name: "Dyana",
    email: "dpaddison7@clickbank.net",
    gender: "Female",
    dates: "2022-12-08",
  },
  {
    id: 9,
    first_name: "Bradly",
    email: "bthurbon8@nyu.edu",
    gender: "Male",
    dates: "2022-12-09",
  },
  {
    id: 10,
    first_name: "Valentine",
    email: "vfranies9@webs.com",
    gender: "Female",
    dates: "2022-12-10",
  },
  {
    id: 11,
    first_name: "Pattie",
    email: "prisbridgea@google.nl",
    gender: "Female",
    dates: "2022-12-11",
  },
  {
    id: 12,
    first_name: "Kathrine",
    email: "ksegeswoethb@parallels.com",
    gender: "Female",
    dates: "2022-12-12",
  },
  {
    id: 13,
    first_name: "Armando",
    email: "ahextc@sbwire.com",
    gender: "Male",
    dates: "2022-12-13",
  },
  {
    id: 14,
    first_name: "Klaus",
    email: "ksleightholmed@umich.edu",
    gender: "Male",
    dates: "2022-12-14",
  },
  {
    id: 15,
    first_name: "Staford",
    email: "scannicotte@booking.com",
    gender: "Male",
    dates: "2022-12-15",
  },
  {
    id: 16,
    first_name: "Paulette",
    email: "psoansf@surveymonkey.com",
    gender: "Female",
    dates: "2022-12-16",
  },
  {
    id: 17,
    first_name: "Kimberly",
    email: "klardnarg@foxnews.com",
    gender: "Agender",
    dates: "2022-12-17",
  },
  {
    id: 18,
    first_name: "Lorrayne",
    email: "lswannellh@nature.com",
    gender: "Female",
    dates: "2022-12-18",
  },
  {
    id: 19,
    first_name: "Kaylee",
    email: "kveldeni@kickstarter.com",
    gender: "Female",
    dates: "2022-12-19",
  },
  {
    id: 20,
    first_name: "Becca",
    email: "bcamidgej@cornell.edu",
    gender: "Female",
    dates: "2022-12-20",
  },
  {
    id: 21,
    first_name: "Wendel",
    email: "wgoodfellowk@msn.com",
    gender: "Male",
    dates: "2022-12-21",
  },
  {
    id: 22,
    first_name: "Lauraine",
    email: "laffleckl@time.com",
    gender: "Female",
    dates: "2022-12-22",
  },
  {
    id: 23,
    first_name: "Kania",
    email: "kpinnegarm@domainmarket.com",
    gender: "Female",
    dates: "2022-12-23",
  },
  {
    id: 24,
    first_name: "Gwenneth",
    email: "gohickeen@omniture.com",
    gender: "Female",
    dates: "2022-12-24",
  },
  {
    id: 25,
    first_name: "Had",
    email: "hmackibbono@typepad.com",
    gender: "Male",
    dates: "2022-12-25",
  },
  {
    id: 26,
    first_name: "Kahlil",
    email: "kbedissp@deviantart.com",
    gender: "Male",
    dates: "2022-12-26",
  },
  {
    id: 27,
    first_name: "Aline",
    email: "alangq@forbes.com",
    gender: "Female",
    dates: "2022-12-27",
  },
  {
    id: 28,
    first_name: "Carlita",
    email: "cethridger@illinois.edu",
    gender: "Female",
    dates: "2022-12-27",
  },
  {
    id: 29,
    first_name: "Jason",
    email: "jsipsons@mlb.com",
    gender: "Male",
    dates: "2022-12-28",
  },
  {
    id: 30,
    first_name: "Davin",
    email: "dweavillt@yandex.ru",
    gender: "Bigender",
    dates: "2022-12-29",
  },
  {
    id: 31,
    first_name: "Kacey",
    email: "kmattsu@bbb.org",
    gender: "Female",
    dates: "2022-12-30",
  },
  {
    id: 32,
    first_name: "Kascey",
    email: "kmattsu@bbsb.org",
    gender: "Femalse",
    dates: "2022-12-31",
  },
];

export default randonData;

export const RegisreationsTableData = [
  {
    id: 1,
    displayName: "Bernardine",
    mobileNumber: "269-165-3681",
    agentName: "Hadden",
    adjudicatorName: "Kilifi",
    status: "KES",
    createdAt: "6:00 PM",
  },
  {
    id: 2,
    displayName: "Rachael",
    mobileNumber: "254-557-1749",
    agentName: "Rawes",
    adjudicatorName: "Bayan",
    status: "MNT",
    createdAt: "2:15 AM",
  },
  {
    id: 3,
    displayName: "Leia",
    mobileNumber: "978-640-5874",
    agentName: "Dullaghan",
    adjudicatorName: "Kentville",
    status: "CAD",
    createdAt: "9:44 AM",
  },
  {
    id: 4,
    displayName: "Symon",
    mobileNumber: "619-195-4909",
    agentName: "Hartness",
    adjudicatorName: "Carmen de Viboral",
    status: "COP",
    createdAt: "7:00 PM",
  },
  {
    id: 5,
    displayName: "Ab",
    mobileNumber: "743-583-2561",
    agentName: "Manchester",
    adjudicatorName: "Kapsabet",
    status: "KES",
    createdAt: "10:34 PM",
  },
  {
    id: 6,
    displayName: "Liza",
    mobileNumber: "773-932-2849",
    agentName: "Herculeson",
    adjudicatorName: "Basqal",
    status: "AZN",
    createdAt: "7:31 AM",
  },
  {
    id: 7,
    displayName: "Elana",
    mobileNumber: "770-415-9775",
    agentName: "Van der Beken",
    adjudicatorName: "Lawrenceville",
    status: "USD",
    createdAt: "9:30 PM",
  },
  {
    id: 8,
    displayName: "Kathe",
    mobileNumber: "609-865-7022",
    agentName: "Quinlan",
    adjudicatorName: "Asíni",
    status: "EUR",
    createdAt: "5:52 PM",
  },
  {
    id: 9,
    displayName: "Brig",
    mobileNumber: "161-828-1382",
    agentName: "Nutton",
    adjudicatorName: "Brataj",
    status: "ALL",
    createdAt: "12:09 AM",
  },
  {
    id: 10,
    displayName: "Guillemette",
    mobileNumber: "785-773-9546",
    agentName: "Bleckly",
    adjudicatorName: "Piru",
    status: "IDR",
    createdAt: "8:46 PM",
  },
  {
    id: 11,
    displayName: "Lory",
    mobileNumber: "487-629-7341",
    agentName: "Robben",
    adjudicatorName: "Ústí nad Orlicí",
    status: "CZK",
    createdAt: "5:57 AM",
  },
  {
    id: 12,
    displayName: "Tommy",
    mobileNumber: "712-348-1786",
    agentName: "Gladwish",
    adjudicatorName: "Barberton",
    status: "ZAR",
    createdAt: "9:35 AM",
  },
  {
    id: 13,
    displayName: "Edwin",
    mobileNumber: "154-266-1106",
    agentName: "Kunz",
    adjudicatorName: "Cosquín",
    status: "ARS",
    createdAt: "12:48 PM",
  },
  {
    id: 14,
    displayName: "Herby",
    mobileNumber: "647-888-5837",
    agentName: "Charlotte",
    adjudicatorName: "Eqbālīyeh",
    status: "IRR",
    createdAt: "12:49 AM",
  },
  {
    id: 15,
    displayName: "Davidson",
    mobileNumber: "675-722-5398",
    agentName: "Boundley",
    adjudicatorName: "Zouma",
    status: "CNY",
    createdAt: "9:46 PM",
  },
  {
    id: 16,
    displayName: "Tally",
    mobileNumber: "987-283-4425",
    agentName: "Stonestreet",
    adjudicatorName: "Rat Burana",
    status: "THB",
    createdAt: "1:44 AM",
  },
  {
    id: 17,
    displayName: "Sigvard",
    mobileNumber: "291-446-4593",
    agentName: "Cleverly",
    adjudicatorName: "Yongjiang",
    status: "CNY",
    createdAt: "5:35 PM",
  },
  {
    id: 18,
    displayName: "Sheilah",
    mobileNumber: "267-245-4304",
    agentName: "Dimmick",
    adjudicatorName: "Shuangzhong",
    status: "CNY",
    createdAt: "3:01 AM",
  },
  {
    id: 19,
    displayName: "Virginia",
    mobileNumber: "107-740-2154",
    agentName: "Forsard",
    adjudicatorName: "Baoziba",
    status: "CNY",
    createdAt: "10:07 PM",
  },
  {
    id: 20,
    displayName: "Ginni",
    mobileNumber: "364-229-4824",
    agentName: "Koppe",
    adjudicatorName: "Potelych",
    status: "UAH",
    createdAt: "9:17 PM",
  },
  {
    id: 21,
    displayName: "Goldie",
    mobileNumber: "405-743-0909",
    agentName: "Poplee",
    adjudicatorName: "Ninomiya",
    status: "JPY",
    createdAt: "8:39 AM",
  },
  {
    id: 22,
    displayName: "Towney",
    mobileNumber: "235-146-4926",
    agentName: "Heineking",
    adjudicatorName: "Kaliro",
    status: "UGX",
    createdAt: "11:35 PM",
  },
  {
    id: 23,
    displayName: "Chrotoem",
    mobileNumber: "779-946-3445",
    agentName: "Learman",
    adjudicatorName: "Mabalacat",
    status: "PHP",
    createdAt: "4:53 PM",
  },
  {
    id: 24,
    displayName: "Cornall",
    mobileNumber: "320-850-6472",
    agentName: "Ricciardello",
    adjudicatorName: "Wyszków",
    status: "PLN",
    createdAt: "6:06 AM",
  },
  {
    id: 25,
    displayName: "Eirena",
    mobileNumber: "592-886-1597",
    agentName: "Mahoney",
    adjudicatorName: "Gaur",
    status: "NPR",
    createdAt: "5:29 PM",
  },
  {
    id: 26,
    displayName: "Warren",
    mobileNumber: "402-425-6569",
    agentName: "Cast",
    adjudicatorName: "Vojnić",
    status: "HRK",
    createdAt: "9:02 PM",
  },
  {
    id: 27,
    displayName: "Yves",
    mobileNumber: "941-531-5407",
    agentName: "Waterfall",
    adjudicatorName: "Pajak",
    status: "IDR",
    createdAt: "4:00 AM",
  },
  {
    id: 28,
    displayName: "Sully",
    mobileNumber: "199-281-4451",
    agentName: "Drummond",
    adjudicatorName: "Guanshui",
    status: "CNY",
    createdAt: "6:18 AM",
  },
  {
    id: 29,
    displayName: "Delia",
    mobileNumber: "957-616-4684",
    agentName: "Chupin",
    adjudicatorName: "Dadiya",
    status: "NGN",
    createdAt: "5:11 PM",
  },
  {
    id: 30,
    displayName: "Elita",
    mobileNumber: "372-547-7857",
    agentName: "Shafto",
    adjudicatorName: "Rennes",
    status: "EUR",
    createdAt: "4:10 PM",
  },
  {
    id: 31,
    displayName: "Chryste",
    mobileNumber: "429-151-7683",
    agentName: "Roblou",
    adjudicatorName: "Erada",
    status: "EUR",
    createdAt: "12:10 AM",
  },
  {
    id: 32,
    displayName: "Crosby",
    mobileNumber: "180-819-7095",
    agentName: "Suttell",
    adjudicatorName: "Itéa",
    status: "EUR",
    createdAt: "5:44 PM",
  },
];
export const AuditTrailTableData = [
  {
    id: 1,
    eventTypeSpecificAttributes: "Hadden",
    eventType: "Kilifi",
    createdAt: "6:00 PM",
  },
  {
    id: 2,
    eventTypeSpecificAttributes: "Hadden",
    eventType: "Kilifi",
    createdAt: "6:00 PM",
  },
  {
    id: 3,
    eventTypeSpecificAttributes: "Hadden",
    eventType: "Kilifi",
    createdAt: "6:00 PM",
  },
  {
    id: 4,
    eventTypeSpecificAttributes: "Hadden",
    eventType: "Kilifi",
    createdAt: "6:00 PM",
  },
  {
    id: 5,
    eventTypeSpecificAttributes: "Hadden",
    eventType: "Kilifi",
    createdAt: "6:00 PM",
  },
  {
    id: 6,
    eventTypeSpecificAttributes: "Hadden",
    eventType: "Kilifi",
    createdAt: "6:00 PM",
  },
  {
    id: 7,
    eventTypeSpecificAttributes: "Hadden",
    eventType: "Kilifi",
    createdAt: "6:00 PM",
  },
  {
    id: 8,
    eventTypeSpecificAttributes: "Hadden",
    eventType: "Kilifi",
    createdAt: "6:00 PM",
  },
  {
    id: 9,
    eventTypeSpecificAttributes: "Hadden",
    eventType: "Kilifi",
    createdAt: "6:00 PM",
  },
  {
    id: 10,
    eventTypeSpecificAttributes: "Hadden",
    eventType: "Kilifi",
    createdAt: "6:00 PM",
  },
  {
    id: 11,
    eventTypeSpecificAttributes: "Hadden",
    eventType: "Kilifi",
    createdAt: "5:57 AM",
  },
  {
    id: 12,
    eventTypeSpecificAttributes: "Hadden",
    eventType: "Kilifi",
    createdAt: "9:35 AM",
  },
  {
    id: 13,
    eventTypeSpecificAttributes: "Hadden",
    eventType: "Kilifi",
    createdAt: "12:48 PM",
  },
  {
    id: 14,
    eventTypeSpecificAttributes: "Hadden",
    eventType: "Kilifi",
    createdAt: "12:49 AM",
  },
  {
    id: 15,
    eventTypeSpecificAttributes: "Hadden",
    eventType: "Kilifi",
    createdAt: "9:46 PM",
  },
  {
    id: 16,
    eventTypeSpecificAttributes: "Hadden",
    eventType: "Kilifi",
    createdAt: "1:44 AM",
  },
  {
    id: 17,
    eventTypeSpecificAttributes: "Hadden",
    eventType: "Kilifi",
    createdAt: "5:35 PM",
  },
  {
    id: 18,
    eventTypeSpecificAttributes: "Hadden",
    eventType: "Kilifi",
    createdAt: "3:01 AM",
  },
  {
    id: 19,
    eventTypeSpecificAttributes: "Hadden",
    eventType: "Kilifi",
    createdAt: "10:07 PM",
  },
  {
    id: 20,
    eventTypeSpecificAttributes: "Hadden",
    eventType: "Kilifi",
    createdAt: "9:17 PM",
  },
  {
    id: 21,
    eventTypeSpecificAttributes: "Hadden",
    eventType: "Kilifi",
    createdAt: "8:39 AM",
  },
  {
    id: 22,
    eventTypeSpecificAttributes: "Hadden",
    eventType: "Kilifi",
    createdAt: "11:35 PM",
  },
  {
    id: 23,
    eventTypeSpecificAttributes: "Hadden",
    eventType: "Kilifi",
    createdAt: "4:53 PM",
  },
  {
    id: 24,
    eventTypeSpecificAttributes: "Hadden",
    eventType: "Kilifi",
    createdAt: "6:06 AM",
  },
  {
    id: 25,
    eventTypeSpecificAttributes: "Hadden",
    eventType: "Kilifi",
    createdAt: "5:29 PM",
  },
  {
    id: 26,
    eventTypeSpecificAttributes: "Hadden",
    eventType: "Kilifi",
    createdAt: "9:02 PM",
  },
  {
    id: 27,
    eventTypeSpecificAttributes: "Hadden",
    eventType: "Kilifi",
    createdAt: "4:00 AM",
  },
  {
    id: 28,
    eventTypeSpecificAttributes: "Hadden",
    eventType: "Kilifi",
    createdAt: "6:18 AM",
  },
  {
    id: 29,
    eventTypeSpecificAttributes: "Hadden",
    eventType: "Kilifi",
    createdAt: "5:11 PM",
  },
  {
    id: 30,
    eventTypeSpecificAttributes: "Hadden",
    eventType: "Kilifi",
    createdAt: "4:10 PM",
  },
  {
    id: 31,
    eventTypeSpecificAttributes: "Hadden",
    eventType: "Kilifi",
    createdAt: "12:10 AM",
  },
  {
    id: 32,
    eventTypeSpecificAttributes: "Hadden",
    eventType: "Kilifi",
    createdAt: "5:44 PM",
  },
];
